version: '3.8'

services:
  app:
    container_name: library-system
    build:
        context: docker-library-system
        dockerfile: Dockerfile
    image: library-system:latest
   # build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/librarydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
